### PR TITLE
Fix #3 Travis selenium intermittent fails

### LINKED ISSUE #3: Travis tests failing sometimes
Tests fail on travis sometimes, I wasn't able to reproduce it:

```
  hoodie.account
  ✓ .isSignedIn returns false (307ms)
  ✓ .id persist page reload (1409ms)
  ✓ .signIn(options) with invalid credentials (402ms)
  ✓ signUp(options) (717ms)
  ✓ signIn(options) (683ms)
  ✓ .id does not change after signUp & signIn (324ms)
  ✓ .username set after signIn (283ms)
  ✓ .isSignedIn() returns true after signIn (298ms)
  ✓ .update({password: newPassword}) resolves with account properties (878ms)
    - .update({username: newUsername}) resolves with account properties
      https://github.com/hoodiehq/hoodie-account-server/issues/79
  ✓ .signOut() resolves with account properties (693ms)
  ✓ .id changes after .signOut() (277ms)
  ✓ .id gets set after signIn (380ms)
  ✓ .destroy() resolves with account properties (672ms)
  ✓ .id changes after .destroy() (297ms)
[17:41:39]:  ERROR  ServerError unknown error: Cannot set property 'id' of undefined
RuntimeError: unknown error: Cannot set property 'id' of undefined 
    at execute(<Function>) - integration.js:355:6 
[17:41:39]:  ERROR  ServerError expected 'Error' to equal 'UnauthorizedError'
Error: expected 'Error' to equal 'UnauthorizedError' 
    at execute(<Function>) - integration.js:355:6 
  1) .fetch with UnauthorizedError
  2) .hasInvalidSession()
  ✓ .signIn() when unauthenticated (675ms)
  15 passing (50s)
  1 pending
  2 failing
  1) hoodie.account .fetch with UnauthorizedError:
      undefined: expected 'Error' to equal 'UnauthorizedError'
      + expected - actual
      -Error
      +UnauthorizedError


  2) hoodie.account .hasInvalidSession():
     undefined: expected null to equal true

```

### PR DESCRIPTION
**Pull request by minrwhite**
This attempts to resolve the timing issues categorized by errors of [this type](https://travis-ci.org/hoodiehq/hoodie-account/builds/167970252) (but not [this type](https://travis-ci.org/hoodiehq/hoodie-account/builds/169432225), which seems to be resulting from a sauce labs connection issue) by introducing a delay before the value of the localStorage in the selenium-controlled client is retrieved and set.

I approached this by trying to recreate the conditions by calling sauce labs from my local machine, and then to fix it by retrying the `getItem` call after a delay. I had one instance where, within the client's executable context, the value of `account` had been retrieved without the `session` key, and then after a delay, the value of account retrieved then had the `session` key set.

### CODE REVIEW

File: test/integration.js [hunk 1]
```diff
@@ -242,7 +242,7 @@ describe('hoodie.account', function () {
     .then(function (account) {
       expect(account.username).to.equal(newUsername)
       expect(account.id).to.match(/^\w+$/)
-      expect(Object.keys(account).sort()).to.deep.equal(['craetedAt', 'id', 'signedUpAt', 'username'])
+      expect(Object.keys(account).sort()).to.deep.equal(['createdAt', 'id', 'signedUpAt', 'username'])
```
Comment (gr2m) [inline test/integration.js:245]: ooops good catch 👍

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
progress! Thanks a ton!
